.PHONY: run-dev
run-dev:
	go run ./cmd --target-address "Fb7KKBmjgKJh1N3aDUxLTj6TR3exH8Xi368bJ3AcDd5T"

.PHONY: run-prod
run-prod:
	go run ./cmd --target-address "Fb7KKBmjgKJh1N3aDUxLTj6TR3exH8Xi368bJ3AcDd5T" --is-mainnet
